# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerID'
          repository: 'minimalapidocker'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
   
     
       
