version: '3.4'

services:
  minimalapidocker:
    image: ${DOCKER_REGISTRY-}minimalapidocker
    build:
      context: .
      dockerfile: MinimalAPIDocker/Dockerfile
  mongo:
   image: mongo
  mongo-express:
    image: mongo-express