version: '3.4'

services:
  minimalapidocker:
    image: minimalapidocker:dev
    build:
      target: build-env
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "MinimalAPIDocker"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\TRPOS\Desktop\MicroServices\MongoDbTrailer2\MinimalAPIDocker\MinimalAPIDocker:/app
      - C:\Users\TRPOS\Desktop\MicroServices\MongoDbTrailer2\MinimalAPIDocker\.:/src
      - C:\Users\TRPOS\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\TRPOS\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net5.0/MinimalAPIDocker.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true